#!/bin/bash

# Run React in the background
cd healthyonthehill && npm start &

# Run Go server in the background
cd api/bruingym-activity-level && go run . &

# Wait for both processes to finish
wait

