#!/bin/bash

# Run React in the background
cd HOTH-client && npm start &

# Run Go server in the background
cd api/bruingym-activity-level && go run . &

# Run Go server in the background
cd api/dining && go run . &

# Run Node.js server for user authentication in the background
cd HOTH-server && node server.js &

# Wait for both processes to finish
wait

