POST https://localhost:4000/api/users/auth/register
Content-type: application/json


###

POST http://localhost:4000/api/users/auth/login
Content-Type: application/json

{
  "email": "edavis05@ucla.edu",
  "password": "EmmaPass1234"
}


###
PATCH http://localhost:4000/api/gymBuddy/update
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NzRkMTVjMTczN2JhYzEzODI0NDQ2OTQiLCJpYXQiOjE3MzMxMTQyOTF9.laergK2cqnjN50pQbXx3gUmNK1ygB6qmW6ZEALoBrJc
Content-Type: application/json

{
  "fitnessLevel": "Intermediate",
  "goal": "Weight Loss",
  "availability": {"day": "Friday", "times": ["Morning", "Evening"]},
  "gymPreference": "BFit",
  "motivationStyle": "Competitive",
  "contact": {"phone": "510-324-3450"}
}

###
GET http://localhost:4000/api/users/
Content-Type: application/json

###
GET http://localhost:4000/api/gymBuddy/getProfile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NzRkMTVjMTczN2JhYzEzODI0NDQ2OTQiLCJpYXQiOjE3MzMxMjEyMzF9.jkJ8BjzyqfgNE3-HRptnBdmjzFboSGySvXtUYrVDqC4


###
PATCH http://localhost:4000/api/gymBuddy/match
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NzRkNmQwMzAyMDI1OGE5MTVmZDJkNzYiLCJpYXQiOjE3MzMxMjc0NTV9.jZiVAJeA9Gt2qc6FcreTdjsGxOa1q-xgVSkqbUx0Cfo

###
PATCH http://localhost:4000/api/gymBuddy/like/674d6d03020258a915fd2d76
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NzRkNmQwMzAyMDI1OGE5MTVmZDJkNjkiLCJpYXQiOjE3MzMxMjkzMDB9.swW3sJNGIw9L43SuDwL9Le8zWLC7y2HCQcYcksyM6X4

###
PATCH http://localhost:4000/api/gymBuddy/dislike/674d6d04020258a915fd2d86"
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NzRkNmQwMzAyMDI1OGE5MTVmZDJkNzYiLCJpYXQiOjE3MzMxMzA4MTR9.8zTcvkexRfOvWmOjwP-oS0Ty12Z28uyLTfyw9xMRJNs

###
DELETE http://localhost:4000/api/gymBuddy/delete/674d14e2737bac138244467b

###
GET http://localhost:4000/api/gymBuddy/getMyBuddies
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NzRkNmQwMzAyMDI1OGE5MTVmZDJkNzYiLCJpYXQiOjE3MzMxMzM2NjB9.VmHjps6SbzTX5AHqrCg-zYT-7BhTWYi4FNoDtPINMpE